# Setup
title:               Computational Matters
tagline:             'Blog'
description:         'Hi There,<p> I am Software Engineer with Masters in CSE, IIIT Hyderabad, Served in Startups,MNC</p> <p>Here are few thoughts logged '
url:                 https://mahatt.github.io/
baseurl:             ''
paginate:            40
permalink:           pretty

# About/contact
author:
  name:              Mahesh Attarde
  url:               https://linkedin.com/maheshattarde
  email:             Fooling_spam_bot@gmail.com

# Gems
plugins:
  - jekyll-paginate

paginate_path: "/blog/page:num/"
plugins_dir: ./_plugins